name: Publish to GHCR (latest)

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 9 * * *"   # 02:00 America/Los_Angeles (PDT)
    - cron: "0 21 * * *"  # 14:00 America/Los_Angeles (PDT)
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install hadolint and yamllint
        run: |
          sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo chmod +x /usr/local/bin/hadolint
          sudo apt-get update && sudo apt-get install -y yamllint
      - name: Run hadolint on Dockerfile
        run: hadolint Dockerfile
      - name: Run yamllint on docker-compose.yml
        run: yamllint docker-compose.yml

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute image name (lowercase)
        id: prep
        run: |
          OWNER_LOWER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          REPO_LOWER=$(echo "${GITHUB_REPOSITORY#*/}" | tr '[:upper:]' '[:lower:]')
          echo "owner_lower=${OWNER_LOWER}" >> $GITHUB_OUTPUT
          echo "repo_lower=${REPO_LOWER}" >> $GITHUB_OUTPUT
          echo "image=${{ env.REGISTRY }}/${OWNER_LOWER}/${REPO_LOWER}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.prep.outputs.image }}:latest
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Show pushed image
        run: echo "Pushed ${{ steps.prep.outputs.image }}:latest"

      - name: Export compose template with image placeholders filled
        run: |
          sed -e "s#\${OWNER_LOWER}#${{ steps.prep.outputs.owner_lower }}#g"               -e "s#\${REPO_LOWER}#${{ steps.prep.outputs.repo_lower }}#g"               docker-compose.yml > docker-compose.rendered.yml
          echo "Rendered docker-compose.rendered.yml"
          cat docker-compose.rendered.yml
